exports.userStatus = {
    APPLIED: "APPLIED",
    IN_PROGRESS: "IN_PROGRESS",
    VERIFIED: "VERIFIED",
    REJECTED: "REJECTED",
    LEFT_THE_COMMUNITY: "LEFT_THE_COMMUNITY",
    DEPARTED: "DEPARTED"
}

exports.userRole = {
    PRESIDENT: "PRESIDENT",
    RESIDENT: "RESIDENT",
    TENANT: "TENANT",
    DEVELOPER: "DEVELOPER",
    OTHERS: "OTHERS",
}